// Configuration constants for Disagall Viewer

export const CONFIG = {
  DEFAULT_PADDING: 24,
  STORAGE_KEY_PADDING: 'defaultPadding',
  STORAGE_KEY_AUTO_OPEN: 'disagall_auto_open',
  TOAST_DURATION: 1800,
  POST_NAV_DELAY: 150,
  AUTO_OPEN_MAX_ATTEMPTS: 15,
  AUTO_OPEN_POLL_INTERVAL: 150,
  RECOMMEND_SYNC_DELAYS: [500, 1200],
  RECOMMEND_THROTTLE_MS: 1200,
  NO_PHOTO_NOTICE_DURATION: 8000
};
